KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="K4fk4_Adm1n_2024!@#$%"
    user_admin="K4fk4_Adm1n_2024!@#$%"
    user_kuber_kafka_user="K4fk4_Pr0d_2024!@#$%";
};