spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/kuber?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Kalit@1579
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        transaction:
          jta:
            platform: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    com.kuber: DEBUG
